apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    database: "[apm-]YYYY.MM.DD"
    url: http://elasticsearch:9200
    jsonData:
      interval: Daily
      timeField: "@timestamp"
      esVersion: 7.13.0
      maxConcurrentShardRequests: 5
      logMessageField: message
      logLevelField: level

  - name: Elasticsearch Metrics
    type: elasticsearch
    access: proxy
    database: "metricbeat-*"
    url: http://elasticsearch:9200
    jsonData:
      interval: Daily
      timeField: "@timestamp"
      esVersion: 7.13.0
      maxConcurrentShardRequests: 5

  - name: Elasticsearch Logs
    type: elasticsearch
    access: proxy
    database: "filebeat-*"
    url: http://elasticsearch:9200
    jsonData:
      interval: Daily
      timeField: "@timestamp"
      esVersion: 7.13.0
      maxConcurrentShardRequests: 5
      logMessageField: message
      logLevelField: level 