services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: elastic_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - observability
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  gateway:
    build: ./app/gateway
    ports:
      - "8000:8000"
    networks:
      - observability

  cliente_api:
    build: ./app/cliente_api
    ports:
      - "8001:8000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: elastic_db
      POSTGRES_HOST: postgres
      DATABASE_URL: postgresql://postgres:postgres@postgres/elastic_db
      API_HOST: 0.0.0.0
      API_PORT: 8000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - observability

  pedido_api:
    build: ./app/pedido_api
    ports:
      - "8002:8000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: elastic_db
      POSTGRES_HOST: postgres
      DATABASE_URL: postgresql://postgres:postgres@postgres/elastic_db
      API_HOST: 0.0.0.0
      API_PORT: 8000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - observability

  entrega_api:
    build: ./app/entrega_api
    ports:
      - "8003:8000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: elastic_db
      POSTGRES_HOST: postgres
      DATABASE_URL: postgresql://postgres:postgres@postgres/elastic_db
      API_HOST: 0.0.0.0
      API_PORT: 8000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - observability
  
  frontend:
    build: ./app/frontend
    ports:
      - "8080:80"
    volumes:
      - /var/log/apache2:/var/log/apache2
    networks:
      - observability

networks:
  observability:
    external: true
    name: observability

volumes:
  postgres_data:
