filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/apache2/*.log

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1

setup.kibana:
  host: "kibana:5601"

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  indices:
    - index: "apache-logs-%{+yyyy.MM.dd}"

logging.level: info
